/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UML.Diagrammer.desktop;

import UML.Diagrammer.backend.apis.Database_Client;
import javafx.scene.control.Button;
import javafx.scene.input.KeyCode;
import javafx.scene.input.MouseButton;
import org.javalite.activejdbc.test.DBSpec;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.testfx.api.FxRobot;
import org.testfx.api.FxToolkit;
import org.testfx.framework.junit5.ApplicationTest;

import java.util.concurrent.TimeoutException;

import static org.testfx.api.FxAssert.verifyThat;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class AppTest extends DBSpec {
    private FxRobot robo;
    private Database_Client dbClient;
    @BeforeEach
    public void setRobo() throws Exception{
        ApplicationTest.launch(App.class);
        robo = new FxRobot();

        String jUnitUrl = "jdbc:mysql://ls-a9db0e6496e5430883b43e690a26b7676cf9d7af.cuirr4jp1g1o.us-west-2.rds.amazonaws.com/junit?useSSL=false";
        String databaseUser = "root";
        String databasePassword = "TeamOverZero";
        int javalinPort = 8888;
        dbClient = new Database_Client(jUnitUrl, databaseUser, databasePassword, javalinPort);
        dbClient.spinUp();

    }

    @AfterEach
    public void reset() throws TimeoutException{
        FxToolkit.hideStage();
        robo.release(new KeyCode[]{});
        robo.release(new MouseButton[]{});
        dbClient.spinDown();
    }


    @Test
    public void largeTest() {

        robo.clickOn("Register New Account");

        robo.clickOn("#registerUserName").write("junittest");
        robo.clickOn("#registerNewPassword").write("password");
        robo.clickOn("#registerConfirmPassword").write("password");

        robo.clickOn("Register");
        robo.clickOn("Log In");

        robo.clickOn("#UserNameTextField").write("junittest");
        robo.clickOn("#PasswordTextField").write("password");

        robo.clickOn("Log In");

        robo.clickOn("#newPageNameTextField").write("page");
        robo.clickOn("Create new");

        robo.clickOn("Class");


        verifyThat(robo.lookup("Log Out"), (Button b) -> b.isVisible());
        verifyThat(robo.lookup("Edit"), (Button b) -> b.isVisible());
        verifyThat(robo.lookup("Delete"), (Button b) -> b.isVisible());
        verifyThat("Load", org.testfx.matcher.control.LabeledMatchers.hasText("Load"));

        robo.rightClickOn("Class Name");

        robo.clickOn("Edit name");

        robo.type(KeyCode.S);

        robo.clickOn("Confirm");

        robo.clickOn("s");

        robo.clickOn("Delete");

        robo.clickOn("Oval");

        robo.clickOn("Edit");

        robo.type(KeyCode.E);

        robo.clickOn("Confirm");

        robo.clickOn("Delete");

        robo.clickOn("Line");

        robo.clickOn("Note");

        robo.clickOn("Folder");

        robo.clickOn("Life Line");

        robo.clickOn("Square");

        robo.clickOn("Stick Figure");

        robo.clickOn("Stick Figure Name");

        robo.clickOn("Text Box");

        robo.clickOn("Loop");

        robo.clickOn("Export");

        robo.clickOn("SVG");

        robo.clickOn("Load");
        robo.clickOn("Load");
    }
}
