/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UML.Diagrammer;

import io.javalin.Javalin;


import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import webclient.Client;

public class App extends Application{

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new DefaultNode().getTitle());

//        Javalin app = Javalin.create().start(7070);
//        app.get("/", ctx -> ctx.result("Hello this is a test"));


        //start the web client running
        Client webClient = new Client();

        launch(args);

        webClient.close();
    }

    public void start(Stage primaryStage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("/Board.fxml"));
        primaryStage.setTitle("UML Diagrammer");
        primaryStage.setScene(new Scene(root, 1000, 800));
        primaryStage.show();

    }
}