/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UML.Diagrammer;
import io.javalin.Javalin;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new DefaultNode().getTitle());

        Javalin app = Javalin.create().start(7070);
        app.get("/", ctx -> ctx.result("Hello this is a test"));

    }
}
